export const USERS = [
  {
    id: '1',
    name: 'Sarah Johnson',
    age: 28,
    location: 'New York, NY',
    distance: '5 miles away',
    bio: 'Adventure seeker and coffee enthusiast. Love hiking, photography, and trying new restaurants.',
    images: [
      'https://randomuser.me/api/portraits/women/1.jpg',
      'https://randomuser.me/api/portraits/women/2.jpg',
      'https://randomuser.me/api/portraits/women/3.jpg',
    ],
    interests: ['Travel', 'Photography', 'Cooking', 'Hiking'],
    occupation: 'Marketing Manager',
    education: 'NYU Business School',
  },
  {
    id: '2',
    name: 'Michael Chen',
    age: 31,
    location: 'San Francisco, CA',
    distance: '3 miles away',
    bio: 'Tech entrepreneur by day, amateur chef by night. Looking for someone to share adventures with.',
    images: [
      'https://randomuser.me/api/portraits/men/1.jpg',
      'https://randomuser.me/api/portraits/men/2.jpg',
      'https://randomuser.me/api/portraits/men/3.jpg',
    ],
    interests: ['Technology', 'Cooking', 'Fitness', 'Reading'],
    occupation: 'Software Engineer',
    education: 'Stanford University',
  },
  {
    id: '3',
    name: 'Emma Wilson',
    age: 26,
    location: 'Los Angeles, CA',
    distance: '7 miles away',
    bio: 'Artist and yoga instructor. Passionate about creativity and wellness.',
    images: [
      'https://randomuser.me/api/portraits/women/4.jpg',
      'https://randomuser.me/api/portraits/women/5.jpg',
      'https://randomuser.me/api/portraits/women/6.jpg',
    ],
    interests: ['Art', 'Yoga', 'Meditation', 'Travel'],
    occupation: 'Art Teacher',
    education: 'UCLA Arts',
  },
];